# Generated by Django 3.2.16 on 2022-12-13 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(default='Jeevan Policy 100 days', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('adhar', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('qulification', models.CharField(blank=True, max_length=255)),
                ('pob', models.CharField(blank=True, max_length=255)),
                ('pan', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('AIncome', models.CharField(blank=True, max_length=255)),
                ('climed_amt', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amt_paid', models.FloatField()),
                ('status', models.CharField(choices=[('0', 'Not Allotted'), ('1', 'Pending'), ('2', 'Allotted')], default='0', max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='XDC_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, unique=True)),
                ('privatekey', models.CharField(max_length=255)),
                ('hashes', models.CharField(blank=True, default='[]', max_length=10000)),
                ('amt_paid', models.FloatField(default=0)),
                ('total_amt', models.FloatField(default=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateField(null=True)),
                ('insure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insurer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount_recived', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.FloatField(default=0)),
                ('insurence', models.ManyToManyField(blank=True, to='core.Insurer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('roll', models.CharField(choices=[('0', 'insure'), ('1', 'provider')], default='0', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('profile', models.FileField(upload_to='profile/')),
                ('phone', models.CharField(blank=True, default='0', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('account', models.CharField(blank=True, default='', max_length=255)),
                ('private_key', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim_Insure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clime_form', models.FileField(upload_to='clime form/')),
                ('pan', models.FileField(upload_to='pan/')),
                ('photo', models.FileField(upload_to='pic/')),
                ('adhar', models.FileField(upload_to='adhar/')),
                ('bc', models.FileField(upload_to='birth certificate/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dis', models.CharField(default='', max_length=255)),
                ('clime_hash', models.CharField(blank=True, default='', max_length=1000)),
                ('insure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insurer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
